---
title: "ESM_232_SnowMelt_Model_Colon_Holmes"
author: "Mario Colon"
date: "June 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Library Load

```{r}

library(tidyverse)
library(reshape2)

```
###Load in data

```{r}

snow_inputs <- read_csv("Inputs.csv")

view(snow_inputs)

```

###Load three models

```{r}

source("model_1_warm.R")
source("model_2_ripe.R")
source("model_3_output.R")

```


##Model 1 - Warming Phase

```{r}

warm <- snow_warm(hm = snow_inputs$SWECM, Ts = snow_inputs$`snow surface temperatureC`, ci = 2101, pw = 1000, Tm = 0)

warm = as.data.frame(warm)

warm$time = c(seq(from = 1, to = 696))

warm

ggplot(warm, aes(time, warm)) + 
  geom_line(col = "purple") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Warming Phase")



```


##Model 2 - Ripening Phase

```{r}

ripe <- snow_ripe(hs = snow_inputs$`snow depthCM`, theta_ret = 0.03, pw = 1000, lambda = 0.334)

ripe = as.data.frame(ripe)

ripe$time = c(seq(from = 1, to = 696))

ripe


ggplot(ripe, aes(time, ripe)) + 
  geom_line(col = "cyan") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Ripeing Phase")

```


##Model 3 - Output Phase 

```{r}


output <- snow_output(hm = snow_inputs$SWECM, hwret = 0.03, pw = 1000, lambda = 0.334)

output = as.data.frame(output)

output$time = c(seq(from = 1, to = 696))

output

ggplot(output, aes(time, output)) + 
  geom_line(col = "purple") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Output Phase")

```

###Energy Combination for CUES only 

```{r}

combination_warm_ripe <- merge(warm, ripe, by ="time")
final_combo <- merge(combination_warm_ripe, output, by = "time")

final_combo$energy = final_combo$warm + final_combo$ripe + final_combo$output

final_combo

ggplot(final_combo, aes(time, energy)) + 
  geom_line(col = "cyan") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Overall Snowmelt CUES")

```

#Spatial

```{r}

spatial <- read_csv("spatialinputs.csv")
spatial$burnside_SWE_cm <- spatial$burnside_SWE_mm/10

warm_burnside <- snow_warm(hm = spatial$burnside_SWE_cm, Ts = snow_inputs$`snow surface temperatureC`, ci = 2101, pw = 1000, Tm = 0)
ripe_burnside <- snow_ripe(hs = spatial$burnside_snowdepth_cm, theta_ret = 0.03, pw = 1000, lambda = 0.334)
output_burnside <- snow_output(hm = spatial$burnside_SWE_cm, hwret = 0.03, pw = 1000, lambda = 0.334)


warm_burnside = as.data.frame(warm_burnside)
ripe_burnside = as.data.frame(ripe_burnside)
output_burnside = as.data.frame(output_burnside)

warm_burnside$time = c(seq(from = 1, to = 720))
ripe_burnside$time = c(seq(from = 1, to = 720))
output_burnside$time = c(seq(from = 1, to = 720))

combination_warm_ripe_burnside <- merge(warm_burnside, ripe_burnside, by ="time")
final_combo_burnside <- merge(combination_warm_ripe_burnside, output_burnside, by = "time")

final_combo_burnside$energy = final_combo_burnside$warm + final_combo$ripe + final_combo$output

final_combo_burnside

ggplot(final_combo_burnside, aes(time, energy)) + 
  geom_line(col = "purple") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Overall Snowmelt Burnside")




```


###Sensitivity Analysis


##Climate Change 

#Data change i.e. 3 degrees (C) to snow surface temp

```{r}

snow_inputs$temp_low = snow_inputs$`snow surface temperatureC` - 3 
snow_inputs$temp_high = snow_inputs$`snow surface temperatureC` + 3
 
warm_low <- snow_warm(hm = snow_inputs$SWECM, Ts = snow_inputs$temp_low, ci = 2101, pw = 1000, Tm = 0)
warm_high <- snow_warm(hm = snow_inputs$SWECM, Ts = snow_inputs$temp_raise, ci = 2101, pw = 1000, Tm = 0)

warm_low = as.data.frame(warm_low)
warm_high = as.data.frame(warm_high)

warm_low$time = c(seq(from = 1, to = 696))
warm_high$time = c(seq(from = 1, to = 696))

combination_warm <- merge(warm, warm_high, by ="time")
final_combo_warm <- merge(combination_warm, warm_low, by = "time")

final_combo_warm

ggplot(final_combo_warm, aes(time)) + 
  geom_line(aes(y = warm, col = "warm")) +
  geom_line(aes(y = warm_low, col = "warm_low")) +
  geom_line(aes(y = warm_high, col = "warm_high")) +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Warming Phase with +/- 3C") +
  labs(colour = "Scenarios")
  
```


##Theta_ret change +/- 

```{r}


ripe_low <- snow_ripe(hs = snow_inputs$`snow depthCM`, theta_ret = 0.01, pw = 1000, lambda = 0.334)
ripe_high <- snow_ripe(hs = snow_inputs$`snow depthCM`, theta_ret = 0.05, pw = 1000, lambda = 0.334)


ripe_low = as.data.frame(ripe_low)
ripe_high = as.data.frame(ripe_high)

ripe_low$time = c(seq(from = 1, to = 696))
ripe_high$time = c(seq(from = 1, to = 696))

combination_ripe <- merge(ripe, ripe_high, by ="time")
final_combo_ripe <- merge(combination_ripe, ripe_low, by = "time")

final_combo_ripe

ggplot(final_combo_ripe, aes(time)) + 
  geom_line(aes(y = ripe, col = "ripe")) +
  geom_line(aes(y = ripe_low, col = "ripe_low")) +
  geom_line(aes(y = ripe_high, col = "ripe_high")) +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Ripeing Phase with +/- .02 θret Ratio") +
  labs(colour = "Scenarios")
  



```


Spatial Analysis

Squaw Valley
```{r squaw}

squaw <- read_csv("squaw.csv")
warm_squaw <- snow_warm(hm = squaw$squaw_swe_cm
, Ts = squaw$squaw_snowtemp, ci = 2101, pw = 1000, Tm = 0)

warm_squaw = as.data.frame(warm_squaw)

warm_squaw$time = c(seq(from = 1, to = 696))


ggplot(warm_squaw, aes(time, warm_squaw)) + 
  geom_line(col = "magenta") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirement for Warming Phase\nSquaw Valley")

```

Leavitt Meadows
```{r leavittil}

leavit <- read_csv("leavittil.csv")
warm_leavit <- snow_warm(hm = leavit$leavit_swe_cm, Ts = leavit$leavitt_snowtemp, ci = 2101, pw = 1000, Tm = 0)

warm_leavit = as.data.frame(warm_leavit)

warm_leavit$time = c(seq(from = 1, to = 696))


ggplot(warm_leavit, aes(time, warm_leavit)) + 
  geom_line(col = "blue") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirement for Warming Phase\nLeavitt Meadows")

```

```{r}
burnside <- read_csv("burnside.csv")
warm_burnside <- snow_warm(hm = burnside$burnside_SWE_cm, Ts = burnside$burnside_snowtemp, ci = 2101, pw = 1000, Tm = 0)

warm_burnside = as.data.frame(warm_burnside)

warm_burnside$time = c(seq(from = 1, to = 696))


ggplot(warm_burnside, aes(time, warm_burnside)) + 
  geom_line(col = "darkgreen") +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirement for Warming Phase\nBurnside")

```


merge all three locations energy requirement
```{r}
spatial1 <- merge(warm, warm_burnside, by="time")
spatial2 <- merge(warm_squaw, warm_leavit, by="time")
spatial_final <- merge(spatial1, spatial2, by="time")

ggplot(spatial_final, aes(time)) + 
  geom_line(aes(y = warm, col = "Cues")) +
  geom_line(aes(y = warm_squaw, col = "Squaw Valley")) +
  geom_line(aes(y = warm_burnside, col = "Burnside")) +
  geom_line(aes(y = warm_leavit, col = "Leavitt Meadow")) +
  theme_classic() + 
  ylab("Energy Required (J m-2)") +
  xlab("Time Step") +
  ggtitle("Energy Requirment for Ripeing Phase Across\nVarious Sierra Nevada Snowpacks") +
  labs(colour = "Snowpack")
```



Boxplot attempt
```{r}


Cues <- max(spatial_final$warm, na.rm=TRUE)
Squaw <- max(spatial_final$warm_squaw, na.rm=TRUE)
Burnside <- max(spatial_final$warm_burnside, na.rm=TRUE)
Leavitt <- max(spatial_final$warm_leavit, na.rm=TRUE)


Location <- c('Cues','Squaw', 'Burnside', 'Leavitt')
Energy <- c(7795845380, 6537269904, 4329858456, 479221292)

max_e <- data.frame(Location, Energy)



ggplot(max_e, aes(x = Location, y=Energy, fill=Location)) + 
  geom_bar(stat="identity") +
  theme_classic() + 
  ylab("Maximum Energy Required (J m-2)") +
  xlab("Snow Survey Location") +
  ggtitle("Maximum Energy Input Requirment for Warming Phase Across\nVarious Sierra Nevada Snowpacks") +
  labs(colour = "Snowpack")




```

